// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGtopvsp-ZBR--oNSEka5Rnb2S5QRdjnk',
    appId: '1:517869683615:web:bdccbe1d5c8b4e0abb33aa',
    messagingSenderId: '517869683615',
    projectId: 'english-dojo-146f9',
    authDomain: 'english-dojo-146f9.firebaseapp.com',
    storageBucket: 'english-dojo-146f9.appspot.com',
    measurementId: 'G-CV8KRQQHKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmT1WddR3TrVpk4XaBwI_d6MZJNm0IoJI',
    appId: '1:517869683615:android:ba577d310ff284b1bb33aa',
    messagingSenderId: '517869683615',
    projectId: 'english-dojo-146f9',
    storageBucket: 'english-dojo-146f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXehnWDnOKPvILw3FDzUvJnADa0knuyEI',
    appId: '1:517869683615:ios:439422cb19cd12fcbb33aa',
    messagingSenderId: '517869683615',
    projectId: 'english-dojo-146f9',
    storageBucket: 'english-dojo-146f9.appspot.com',
    iosClientId: '517869683615-7afueok7dj9mtcefa4obi1nsh1h29t3p.apps.googleusercontent.com',
    iosBundleId: 'com.example.englishDojo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXehnWDnOKPvILw3FDzUvJnADa0knuyEI',
    appId: '1:517869683615:ios:439422cb19cd12fcbb33aa',
    messagingSenderId: '517869683615',
    projectId: 'english-dojo-146f9',
    storageBucket: 'english-dojo-146f9.appspot.com',
    iosClientId: '517869683615-7afueok7dj9mtcefa4obi1nsh1h29t3p.apps.googleusercontent.com',
    iosBundleId: 'com.example.englishDojo',
  );
}
